月度标保分析:
  - id: 1
    text: 查询全系统的标保达成、标保达成率、标保同比、全年标保达成、全年标保进度、全年标保同比
    data_source:
      select:
        - 标保达成
        - 标保达成率
        - 标保同比
        - 全年标保达成
        - 全年标保进度
        - 全年标保同比
      from : tests/fixtures/标保.csv
      where :
        - field:  片区
          operator:  eq
          value:  全系统

  - id: 2
    text: 查询标保达成率高于70%的机构
    data_source:
      select: # 列
        - 机构
      from: tests/fixtures/标保.csv
      where: # 筛选行
        - field: 标保达成率
          operator: gt
          value: 70
      order_by:
        - field: 标保达成率
          direction: desc

  - id: 3
    text: 查询标保达成率低于50%的机构
    data_source:
      select: # 列
        - 机构
      from: tests/fixtures/标保.csv
      where: # 筛选行
        - field: 标保达成率
          operator: lt
          value: 50
      order_by:
        - field: 标保达成率
          direction: desc
  - id: 4
    text: 查询全年标保进度高于60%的机构
    data_source:
      select: # 列
        - 机构
      from: tests/fixtures/标保.csv
      where: # 筛选行
        - field: 全年标保进度
          operator: gt
          value: 60
      order_by:
        - field: 全年标保进度
          direction: desc

  - id: 5
    text: 查询全年标保进度低于45%的机构
    data_source:
      select: # 列
        - 机构
      from: tests/fixtures/标保.csv
      where: # 筛选行
        - field: 全年标保进度
          operator: lt
          value: 45
      order_by:
        - field: 全年标保进度
          direction: desc


月度价值分析:
  - id: 1
    text: 查询全系统的价值达成、价值达成率、价值同比、全年价值进度、全年价值同比
    data_source:
      select: # 列
        - 价值达成
        - 价值达成率
        - 价值同比
        - 全年价值进度
        - 全年价值同比
      from: tests/fixtures/价值.csv
      where: # 筛选行
        - field: 片区
          operator:  eq
          value:  全系统

  - id: 2
    text: 查询价值达成率高于85%的机构
    data_source:
      select: # 列
        - 机构
      from: tests/fixtures/价值.csv
      where: # 筛选行
        - field: 价值达成率
          operator: gt
          value: 85
      order_by:
        - field: 价值达成率
          direction: desc

  - id: 3
    text: 查询价值达成率低于55%的机构
    data_source:
      select: # 列
        - 机构
      from: tests/fixtures/价值.csv
      where: # 筛选行
        - field: 价值达成率
          operator: lt
          value: 55
      order_by:
        - field: 价值达成率
          direction: desc
